### ISSUE TITLE
Thirdparty dependency checker issue

### ISSUE THREAD

**Issue by VelpukondaRameshLio** [Nuix/Nuix-Java-Engine-Baseline#10]
Hi

I am working on admin user it is connecting to license server and third party dependency checker working but I am login with user it is not working.

Could you please help me this issue.

Thank you in advance.

NOTE: I gave same permission with User and Admin

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio , I've made some changes to the [ThirdPartyDependencyChecker](https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/d36c63ec3d80aaf6a445b06a52d4b5643458f159/Java/src/main/java/com/nuix/javaenginesimple/ThirdPartyDependencyChecker.java) so that it has some exception handling.  This should help in 2 ways:

- Catch the exception so it doesn't go uncaught and cause things to stop
- Log an error message with a stack trace, which should have some more information as to why you are seeing an error.

If you try again using this updated version of the class, please capture the error it produces and share it here and I can see if I can assist you with it.

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio were you able to get any additional information from the updated version of that class?

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio I am going to close this for now, but if you are still having an issue feel free to re-open the issue or open a new one 😄
