### ISSUE TITLE
Run Project in Offline Enviroment

### ISSUE THREAD

**Issue by gleithoernchen** [Nuix/Nuix-Java-Engine-Baseline#22]
We had several tries and did not succeed in running the project offline. We installed grade locally which worked fine, but when starting it still tries to download some maven stuff. We tried to uncomment some things in the build.gradle.kts file but with no success.
Help is appreciated.
Thanks

**Comment by JuicyDragon** [comment]
Hello @gleithoernchen, please elaborate on what you are trying to do and how you are running it and I can see if I can help you figure out what is going on.

**Comment by gleithoernchen** [comment]
Hello @JuicyDragon, We run it in IntelliJ. We just want to have the setup for developing custom jar files in an offline enviroment. But we struggle with the initial setup. When doing the same in an online enviroment it works but in an offline enviroment during the first build it still tries to download some maven stuff. After the first build was made it works also without internet. But we would like to start it in an offline enviroment the first time...
When i remember right it was that stuff that was being downloaded:
![image](https://github.com/user-attachments/assets/08a23c61-6aaf-407a-bb22-b67a18a5e57f) and also maven which all is mentioned in the build.gradle.kts file.
Thanks

**Comment by JuicyDragon** [comment]
Thank you for the additional details.  I believe what you might try doing is using [mavenLocal](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.artifacts.dsl/-repository-handler/maven-local.html), which is where Maven resolves dependencies from a local cached copy rather than the internet.

First you will want to alter this entry in `build.gradle.kts` on the offline machine:
```kotlin
repositories {
    mavenCentral()
}
```

to instead be the following, telling Gradle that it may also resolve from the local cache:
```kotlin
repositories {
    mavenCentral()  // Could probably remove this if you wanted to, should be no harm in leaving it though
    mavenLocal()  // Specify mavenLocal as valid Maven repository
}
```

On a machine which is connected to the internet, perform a test run to populate all the dependencies in the local cache of that machine.  Then make a copy of the folder `C:\Users\<WINDOWS_USERNAME>\.m2` and copy to appropriate destination folder on offline machine.  I believe the project on the offline machine should then be able to resolve the dependencies from the local cache that you copied over.

**Comment by JuicyDragon** [comment]
Going to close this assuming you got it working using the above suggestion.  If you did not, we can re-open it.

**Comment by gleithoernchen** [comment]
Hi @JuicyDragon,
sorry for the delay in response. Thanks for the input.
I tried but I did not work.
When changing 
```java
repositories {
    mavenCentral()
}
``` 
to 
#
```java
repositories {
    mavenCentral()  // Could probably remove this if you wanted to, should be no harm in leaving it though
    mavenLocal()  // Specify mavenLocal as valid Maven repository
}
``` 
an ran it with internet, it started but the folder C:\Users\<WINDOWS_USERNAME>\.m2 was not created.
After that when trying to run it with internet (for testing)
```java
repositories {
    mavenLocal()
}
``` 
It throws that error that the folder was not found.
![image](https://github.com/user-attachments/assets/85dd89d9-8872-47e1-978a-c5743f24329c)

I also created the .m2 folder manually to see if it gets populated but that was not the case.
Any new ideas?

Thanks
Daniel

**Comment by JuicyDragon** [comment]
No worries about the delay 😄 

I've done some research regarding this.  One potential solution I found was copying the cache to offline machine.  Supposedly the cache resides in `%USERPROFILE%\.gradle` and can be copied to the offline machine once it has been populated by the online machine.  From what I've seen, the path references are absolute so the location on the offline machine must be the same as machine where it was popluated.

So if it was copied from `C:\Users\RSanchez01\.gradle` on the online machine, it must be in `C:\Users\RSanchez01\.gradle` in the offline machine.  I haven't had a chance to test this though.

**Comment by gleithoernchen** [comment]
Yes that works. Thanks.

**Comment by JuicyDragon** [comment]
Glad to hear it.  I'm going to close this then.
